version: 2.1

orbs:
  node: circleci/node@5.0.3

workflows:
  vscode-integration-test:
    jobs:
      - node/run:
          yarn-run: lint-fmt
          version: "16.17.1-browsers"
          pkg-manager: yarn
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          version: "16.17.1-browsers"
          pkg-manager: yarn
          test-results-for: mocha
